---
# Software installation
- name: ensure packages are installed
  apt: pkg={{item}}
  with_items:
    - samba
  tags:
    - backuppc
    - packages

# client setup to allow backuppc access to file system
- name: create backuppc group
  group: name=backuppc state=present
  tags:
    - backuppc
    - user

- name: create backuppc user who will do the work as sudo
  user:
    name=backuppc
    group=backuppc
    password=b4ckuppc
    generate_ssh_key=yes
    ssh_key_comment="ansible-generated-for-{{ ansible_hostname }}"
  when: backuppc_client_server_ip not in ansible_all_ipv4_addresses
  tags:
    - backuppc
    - user

- name: get public ssh key from server
  shell: "ssh-keyscan -t rsa {{ backuppc_client_server_ip }}"
  register: sshkeyscan
  when: backuppc_client_server_ip not in ansible_all_ipv4_addresses
  tags:
    - backuppc
    - ssh

# - debug: var=sshkeyscan.stdout
# - debug: var=sshkeyscan.stdout.split(' ')
# - debug: var=sshkeyscan.stdout.split(' ')|first|length
# - debug: var=sshkeyscan.stdout|truncate((sshkeyscan.stdout.split(' ')|first|length))
# - debug: msg="{{ sshkeyscan.stdout.split(' ')[1] }} {{ sshkeyscan.stdout.split(' ')[2] }}"

- name: add server key to authorized keys
  authorized_key:
    user: backuppc
    key: "{{ sshkeyscan.stdout.split(' ')[1] }} {{ sshkeyscan.stdout.split(' ')[2] }}"
    key_options: "from=\"{{ backuppc_client_server_ip }}\""
  when: sshkeyscan is defined and sshkeyscan|changed
  tags:
    - backuppc
    - ssh

- name: allow sudo access comment
  lineinfile: "dest='/etc/sudoers' insertafter='^%sudo' line='# Allow Back Up PC to {{ backuppc_client_type }}' validate='visudo -cf %s'"
  tags:
    - backuppc
    - user

- name: allow sudo access
  lineinfile: "dest='/etc/sudoers' insertafter='^# Allow Back Up PC to {{ backuppc_client_type }}' line='backuppc  ALL=NOPASSWD: /bin/{{ backuppc_client_type }}' validate='visudo -cf %s'"
  tags:
    - backuppc
    - user